class CityData {
  final String name;
  final String region;
  final String climate;
  final String soilType;
  final List<String> suitableCrops;
  final Map<String, String> climateInfo;

  CityData({
    required this.name,
    required this.region,
    required this.climate,
    required this.soilType,
    required this.suitableCrops,
    required this.climateInfo,
  });

  static final List<CityData> _cities = [
    CityData(
      name: 'Adana',
      region: 'Akdeniz',
      climate: 'Akdeniz',
      soilType: 'Kumlu-Killi Toprak',
      suitableCrops: ['Pamuk', 'Turunçgil', 'Domates', 'Biber', 'Patlıcan', 'Kabak', 'Salatalık', 'Marul'],
      climateInfo: {'Sıcaklık': '8-38°C', 'Yağış': '600-800mm/yıl', 'Nem': 'Yüksek', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Adıyaman',
      region: 'Güneydoğu Anadolu',
      climate: 'Karasal-Akdeniz Geçiş',
      soilType: 'Killi-Kumlu Toprak',
      suitableCrops: ['Antep Fıstığı', 'Üzüm', 'Zeytin', 'Domates', 'Biber', 'Patlıcan', 'Kabak', 'Salatalık'],
      climateInfo: {'Sıcaklık': '0-40°C', 'Yağış': '500-600mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Afyonkarahisar',
      region: 'Ege',
      climate: 'Karasal',
      soilType: 'Killi Toprak',
      suitableCrops: ['Buğday', 'Arpa', 'Şeker Pancarı', 'Ayçiçeği', 'Patates', 'Soğan', 'Havuç', 'Elma'],
      climateInfo: {'Sıcaklık': '-5-35°C', 'Yağış': '400-500mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Yüksek'},
    ),
    CityData(
      name: 'Ağrı',
      region: 'Doğu Anadolu',
      climate: 'Karasal',
      soilType: 'Killi-Asitli Toprak',
      suitableCrops: ['Buğday', 'Arpa', 'Patates', 'Lahana', 'Havuç', 'Soğan', 'Ispanak', 'Maydanoz'],
      climateInfo: {'Sıcaklık': '-25-30°C', 'Yağış': '400-500mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Yüksek'},
    ),
    CityData(
      name: 'Aksaray',
      region: 'İç Anadolu',
      climate: 'Karasal',
      soilType: 'Killi Toprak',
      suitableCrops: ['Buğday', 'Arpa', 'Mısır', 'Ayçiçeği', 'Şeker Pancarı', 'Patates', 'Soğan', 'Havuç'],
      climateInfo: {'Sıcaklık': '-8-38°C', 'Yağış': '300-400mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Yüksek'},
    ),
    CityData(
      name: 'Amasya',
      region: 'Karadeniz',
      climate: 'Karadeniz-Karasal Geçiş',
      soilType: 'Killi-Tınlı Toprak',
      suitableCrops: ['Elma', 'Armut', 'Şeftali', 'Kiraz', 'Domates', 'Biber', 'Patlıcan', 'Salatalık'],
      climateInfo: {'Sıcaklık': '-5-35°C', 'Yağış': '500-600mm/yıl', 'Nem': 'Orta', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Ankara',
      region: 'İç Anadolu',
      climate: 'Karasal',
      soilType: 'Killi Toprak',
      suitableCrops: ['Buğday', 'Arpa', 'Mısır', 'Ayçiçeği', 'Şeker Pancarı', 'Patates', 'Soğan', 'Havuç'],
      climateInfo: {'Sıcaklık': '-5-35°C', 'Yağış': '400-500mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Yüksek'},
    ),
    CityData(
      name: 'Antalya',
      region: 'Akdeniz',
      climate: 'Akdeniz',
      soilType: 'Kumlu-Killi Toprak',
      suitableCrops: ['Turunçgil', 'Avokado', 'Mango', 'Domates', 'Biber', 'Patlıcan', 'Kabak', 'Salatalık'],
      climateInfo: {'Sıcaklık': '12-35°C', 'Yağış': '800-1000mm/yıl', 'Nem': 'Yüksek', 'Rüzgar': 'Düşük'},
    ),
    CityData(
      name: 'Ardahan',
      region: 'Doğu Anadolu',
      climate: 'Karasal',
      soilType: 'Killi-Asitli Toprak',
      suitableCrops: ['Buğday', 'Arpa', 'Patates', 'Lahana', 'Havuç', 'Soğan', 'Ispanak', 'Maydanoz'],
      climateInfo: {'Sıcaklık': '-30-25°C', 'Yağış': '500-600mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Yüksek'},
    ),
    CityData(
      name: 'Artvin',
      region: 'Karadeniz',
      climate: 'Karadeniz',
      soilType: 'Asitli-Killi Toprak',
      suitableCrops: ['Çay', 'Fındık', 'Mısır', 'Fasulye', 'Lahana', 'Karnabahar', 'Brokoli', 'Ispanak'],
      climateInfo: {'Sıcaklık': '3-26°C', 'Yağış': '1300-1600mm/yıl', 'Nem': 'Çok Yüksek', 'Rüzgar': 'Düşük'},
    ),
    CityData(
      name: 'Aydın',
      region: 'Ege',
      climate: 'Akdeniz',
      soilType: 'Kumlu-Killi Toprak',
      suitableCrops: ['İncir', 'Zeytin', 'Üzüm', 'Nar', 'Turunçgil', 'Domates', 'Biber', 'Patlıcan', 'Kabak'],
      climateInfo: {'Sıcaklık': '8-35°C', 'Yağış': '500-600mm/yıl', 'Nem': 'Orta', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Balıkesir',
      region: 'Marmara',
      climate: 'Akdeniz-Karadeniz Geçiş',
      soilType: 'Killi-Tınlı Toprak',
      suitableCrops: ['Zeytin', 'Üzüm', 'Şeftali', 'Kiraz', 'Domates', 'Biber', 'Patlıcan', 'Salatalık', 'Marul'],
      climateInfo: {'Sıcaklık': '4-31°C', 'Yağış': '550-650mm/yıl', 'Nem': 'Orta', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Bartın',
      region: 'Karadeniz',
      climate: 'Karadeniz',
      soilType: 'Killi-Tınlı Toprak',
      suitableCrops: ['Çilek', 'Fındık', 'Mısır', 'Domates', 'Biber', 'Salatalık'],
      climateInfo: {'Sıcaklık': '5-28°C', 'Yağış': '1000-1200mm/yıl', 'Nem': 'Yüksek', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Batman',
      region: 'Güneydoğu Anadolu',
      climate: 'Karasal-Akdeniz Geçiş',
      soilType: 'Killi-Kumlu Toprak',
      suitableCrops: ['Antep Fıstığı', 'Üzüm', 'Zeytin', 'Domates', 'Biber', 'Patlıcan', 'Kabak', 'Salatalık'],
      climateInfo: {'Sıcaklık': '-3-42°C', 'Yağış': '450-550mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Bayburt',
      region: 'Karadeniz',
      climate: 'Karasal',
      soilType: 'Killi-Asitli Toprak',
      suitableCrops: ['Buğday', 'Arpa', 'Patates', 'Lahana', 'Havuç', 'Soğan', 'Ispanak', 'Maydanoz'],
      climateInfo: {'Sıcaklık': '-20-30°C', 'Yağış': '400-500mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Yüksek'},
    ),
    CityData(
      name: 'Bilecik',
      region: 'Marmara',
      climate: 'Marmara-Karasal Geçiş',
      soilType: 'Killi-Kireçli Toprak',
      suitableCrops: ['Şerbetçiotu', 'Buğday', 'Ayçiçeği', 'Domates', 'Üzüm', 'Ceviz'],
      climateInfo: {'Sıcaklık': '-2-32°C', 'Yağış': '500-600mm/yıl', 'Nem': 'Orta', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Bingöl',
      region: 'Doğu Anadolu',
      climate: 'Karasal',
      soilType: 'Killi-Tınlı Toprak',
      suitableCrops: ['Buğday', 'Arpa', 'Ceviz', 'Fasulye', 'Patates', 'Yem Bitkileri'],
      climateInfo: {'Sıcaklık': '-15-32°C', 'Yağış': '600-800mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Yüksek'},
    ),
    CityData(
      name: 'Bitlis',
      region: 'Doğu Anadolu',
      climate: 'Karasal',
      soilType: 'Killi-Asitli Toprak',
      suitableCrops: ['Buğday', 'Arpa', 'Patates', 'Lahana', 'Havuç', 'Soğan', 'Ispanak', 'Maydanoz'],
      climateInfo: {'Sıcaklık': '-20-30°C', 'Yağış': '500-600mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Yüksek'},
    ),
    CityData(
      name: 'Bolu',
      region: 'Karadeniz',
      climate: 'Karadeniz-Karasal Geçiş',
      soilType: 'Killi-Tınlı Toprak',
      suitableCrops: ['Fındık', 'Elma', 'Armut', 'Şeftali', 'Domates', 'Biber', 'Patlıcan', 'Salatalık'],
      climateInfo: {'Sıcaklık': '-5-30°C', 'Yağış': '600-700mm/yıl', 'Nem': 'Orta-Yüksek', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Burdur',
      region: 'Akdeniz',
      climate: 'Akdeniz-Karasal Geçiş',
      soilType: 'Killi-Kumlu Toprak',
      suitableCrops: ['Elma', 'Armut', 'Şeftali', 'Kiraz', 'Domates', 'Biber', 'Patlıcan', 'Salatalık'],
      climateInfo: {'Sıcaklık': '-5-35°C', 'Yağış': '450-550mm/yıl', 'Nem': 'Düşük-Orta', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Bursa',
      region: 'Marmara',
      climate: 'Akdeniz-Karadeniz Geçiş',
      soilType: 'Killi-Tınlı Toprak',
      suitableCrops: ['Şeftali', 'Kiraz', 'Armut', 'Elma', 'Domates', 'Biber', 'Patlıcan', 'Salatalık', 'Marul', 'Ispanak'],
      climateInfo: {'Sıcaklık': '6-30°C', 'Yağış': '650-750mm/yıl', 'Nem': 'Orta-Yüksek', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Çanakkale',
      region: 'Marmara',
      climate: 'Akdeniz-Karadeniz Geçiş',
      soilType: 'Kumlu-Killi Toprak',
      suitableCrops: ['Zeytin', 'Üzüm', 'Domates', 'Biber', 'Patlıcan', 'Salatalık', 'Marul', 'Ispanak'],
      climateInfo: {'Sıcaklık': '5-30°C', 'Yağış': '600-700mm/yıl', 'Nem': 'Orta', 'Rüzgar': 'Yüksek'},
    ),
    CityData(
      name: 'Çankırı',
      region: 'İç Anadolu',
      climate: 'Karasal',
      soilType: 'Killi Toprak',
      suitableCrops: ['Buğday', 'Arpa', 'Mısır', 'Ayçiçeği', 'Şeker Pancarı', 'Patates', 'Soğan', 'Havuç'],
      climateInfo: {'Sıcaklık': '-10-35°C', 'Yağış': '400-500mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Yüksek'},
    ),
    CityData(
      name: 'Çorum',
      region: 'Karadeniz',
      climate: 'Karadeniz-Karasal Geçiş',
      soilType: 'Killi-Tınlı Toprak',
      suitableCrops: ['Buğday', 'Arpa', 'Mısır', 'Ayçiçeği', 'Patates', 'Soğan', 'Havuç', 'Elma'],
      climateInfo: {'Sıcaklık': '-8-35°C', 'Yağış': '500-600mm/yıl', 'Nem': 'Orta', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Denizli',
      region: 'Ege',
      climate: 'Akdeniz-Karasal Geçiş',
      soilType: 'Killi-Kumlu Toprak',
      suitableCrops: ['Üzüm', 'Elma', 'Armut', 'Şeftali', 'Domates', 'Biber', 'Patlıcan', 'Salatalık', 'Marul'],
      climateInfo: {'Sıcaklık': '2-36°C', 'Yağış': '450-550mm/yıl', 'Nem': 'Düşük-Orta', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Diyarbakır',
      region: 'Güneydoğu Anadolu',
      climate: 'Karasal-Akdeniz Geçiş',
      soilType: 'Killi-Kumlu Toprak',
      suitableCrops: ['Antep Fıstığı', 'Üzüm', 'Zeytin', 'Domates', 'Biber', 'Patlıcan', 'Kabak', 'Salatalık'],
      climateInfo: {'Sıcaklık': '-5-42°C', 'Yağış': '450-550mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Düzce',
      region: 'Karadeniz',
      climate: 'Karadeniz',
      soilType: 'Killi-Tınlı Toprak',
      suitableCrops: ['Fındık', 'Elma', 'Armut', 'Şeftali', 'Domates', 'Biber', 'Patlıcan', 'Salatalık'],
      climateInfo: {'Sıcaklık': '2-30°C', 'Yağış': '700-800mm/yıl', 'Nem': 'Yüksek', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Edirne',
      region: 'Marmara',
      climate: 'Akdeniz-Karadeniz Geçiş',
      soilType: 'Kumlu-Killi Toprak',
      suitableCrops: ['Ayçiçeği', 'Buğday', 'Arpa', 'Mısır', 'Domates', 'Biber', 'Patlıcan', 'Kabak'],
      climateInfo: {'Sıcaklık': '0-32°C', 'Yağış': '550-650mm/yıl', 'Nem': 'Orta', 'Rüzgar': 'Yüksek'},
    ),
    CityData(
      name: 'Elazığ',
      region: 'Doğu Anadolu',
      climate: 'Karasal',
      soilType: 'Killi-Asitli Toprak',
      suitableCrops: ['Buğday', 'Arpa', 'Mısır', 'Ayçiçeği', 'Patates', 'Soğan', 'Havuç', 'Elma', 'Armut'],
      climateInfo: {'Sıcaklık': '-10-35°C', 'Yağış': '400-500mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Yüksek'},
    ),
    CityData(
      name: 'Erzincan',
      region: 'Doğu Anadolu',
      climate: 'Karasal',
      soilType: 'Killi-Asitli Toprak',
      suitableCrops: ['Buğday', 'Arpa', 'Mısır', 'Ayçiçeği', 'Patates', 'Soğan', 'Havuç', 'Elma'],
      climateInfo: {'Sıcaklık': '-18-32°C', 'Yağış': '400-500mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Yüksek'},
    ),
    CityData(
      name: 'Erzurum',
      region: 'Doğu Anadolu',
      climate: 'Karasal',
      soilType: 'Killi-Asitli Toprak',
      suitableCrops: ['Buğday', 'Arpa', 'Patates', 'Lahana', 'Havuç', 'Soğan', 'Ispanak', 'Maydanoz'],
      climateInfo: {'Sıcaklık': '-25-30°C', 'Yağış': '400-500mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Yüksek'},
    ),
    CityData(
      name: 'Eskişehir',
      region: 'İç Anadolu',
      climate: 'Karasal',
      soilType: 'Killi-Tınlı Toprak',
      suitableCrops: ['Buğday', 'Arpa', 'Mısır', 'Ayçiçeği', 'Şeker Pancarı', 'Patates', 'Soğan', 'Havuç', 'Elma'],
      climateInfo: {'Sıcaklık': '-8-36°C', 'Yağış': '400-500mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Yüksek'},
    ),
    CityData(
      name: 'Gaziantep',
      region: 'Güneydoğu Anadolu',
      climate: 'Karasal-Akdeniz Geçiş',
      soilType: 'Killi-Kumlu Toprak',
      suitableCrops: ['Antep Fıstığı', 'Üzüm', 'Zeytin', 'Domates', 'Biber', 'Patlıcan', 'Kabak', 'Salatalık'],
      climateInfo: {'Sıcaklık': '2-40°C', 'Yağış': '500-600mm/yıl', 'Nem': 'Orta', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Giresun',
      region: 'Karadeniz',
      climate: 'Karadeniz',
      soilType: 'Asitli-Killi Toprak',
      suitableCrops: ['Fındık', 'Çay', 'Mısır', 'Fasulye', 'Lahana', 'Karnabahar', 'Brokoli', 'Ispanak', 'Maydanoz'],
      climateInfo: {'Sıcaklık': '6-28°C', 'Yağış': '1200-1500mm/yıl', 'Nem': 'Çok Yüksek', 'Rüzgar': 'Düşük'},
    ),
    CityData(
      name: 'Gümüşhane',
      region: 'Karadeniz',
      climate: 'Karadeniz-Karasal Geçiş',
      soilType: 'Killi-Asitli Toprak',
      suitableCrops: ['Buğday', 'Arpa', 'Patates', 'Lahana', 'Havuç', 'Soğan', 'Ispanak', 'Maydanoz'],
      climateInfo: {'Sıcaklık': '-10-28°C', 'Yağış': '500-600mm/yıl', 'Nem': 'Orta', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Hakkâri',
      region: 'Doğu Anadolu',
      climate: 'Karasal',
      soilType: 'Killi-Asitli Toprak',
      suitableCrops: ['Buğday', 'Arpa', 'Patates', 'Lahana', 'Havuç', 'Soğan', 'Ispanak', 'Maydanoz'],
      climateInfo: {'Sıcaklık': '-20-30°C', 'Yağış': '600-700mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Yüksek'},
    ),
    CityData(
      name: 'Hatay',
      region: 'Akdeniz',
      climate: 'Akdeniz',
      soilType: 'Kumlu-Killi Toprak',
      suitableCrops: ['Turunçgil', 'Zeytin', 'Domates', 'Biber', 'Patlıcan', 'Kabak', 'Salatalık', 'Marul', 'Ispanak'],
      climateInfo: {'Sıcaklık': '8-36°C', 'Yağış': '600-800mm/yıl', 'Nem': 'Yüksek', 'Rüzgar': 'Düşük'},
    ),
    CityData(
      name: 'Iğdır',
      region: 'Doğu Anadolu',
      climate: 'Karasal',
      soilType: 'Killi-Kumlu Toprak',
      suitableCrops: ['Kayısı', 'Elma', 'Armut', 'Şeftali', 'Domates', 'Biber', 'Patlıcan', 'Salatalık'],
      climateInfo: {'Sıcaklık': '-15-38°C', 'Yağış': '250-350mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Yüksek'},
    ),
    CityData(
      name: 'Isparta',
      region: 'Akdeniz',
      climate: 'Akdeniz-Karasal Geçiş',
      soilType: 'Killi-Kumlu Toprak',
      suitableCrops: ['Gül', 'Elma', 'Armut', 'Şeftali', 'Domates', 'Biber', 'Patlıcan', 'Salatalık'],
      climateInfo: {'Sıcaklık': '-5-35°C', 'Yağış': '450-550mm/yıl', 'Nem': 'Düşük-Orta', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'İstanbul',
      region: 'Marmara',
      climate: 'Akdeniz-Karadeniz Geçiş',
      soilType: 'Killi-Tınlı Toprak',
      suitableCrops: ['Domates', 'Biber', 'Patlıcan', 'Salatalık', 'Marul', 'Ispanak', 'Maydanoz', 'Fesleğen'],
      climateInfo: {'Sıcaklık': '8-28°C', 'Yağış': '700-800mm/yıl', 'Nem': 'Yüksek', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'İzmir',
      region: 'Ege',
      climate: 'Akdeniz',
      soilType: 'Kumlu-Tınlı Toprak',
      suitableCrops: ['Zeytin', 'Üzüm', 'İncir', 'Nar', 'Turunçgil', 'Domates', 'Biber', 'Patlıcan'],
      climateInfo: {'Sıcaklık': '10-32°C', 'Yağış': '600-700mm/yıl', 'Nem': 'Orta', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Kahramanmaraş',
      region: 'Akdeniz',
      climate: 'Akdeniz-Karasal Geçiş',
      soilType: 'Killi-Kumlu Toprak',
      suitableCrops: ['Kırmızı Biber', 'Domates', 'Biber', 'Patlıcan', 'Kabak', 'Salatalık', 'Marul', 'Ispanak'],
      climateInfo: {'Sıcaklık': '0-38°C', 'Yağış': '500-700mm/yıl', 'Nem': 'Orta', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Karabük',
      region: 'Karadeniz',
      climate: 'Karadeniz-Karasal Geçiş',
      soilType: 'Killi-Tınlı Toprak',
      suitableCrops: ['Fındık', 'Elma', 'Armut', 'Şeftali', 'Domates', 'Biber', 'Patlıcan', 'Salatalık'],
      climateInfo: {'Sıcaklık': '-5-32°C', 'Yağış': '600-700mm/yıl', 'Nem': 'Orta-Yüksek', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Karaman',
      region: 'İç Anadolu',
      climate: 'Karasal',
      soilType: 'Killi-Tuzlu Toprak',
      suitableCrops: ['Buğday', 'Arpa', 'Şeker Pancarı', 'Ayçiçeği', 'Mısır', 'Patates', 'Soğan', 'Havuç'],
      climateInfo: {'Sıcaklık': '-8-38°C', 'Yağış': '300-400mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Yüksek'},
    ),
    CityData(
      name: 'Kars',
      region: 'Doğu Anadolu',
      climate: 'Karasal',
      soilType: 'Killi-Siyah Toprak',
      suitableCrops: ['Arpa', 'Buğday', 'Yem Bitkileri', 'Patates', 'Lahana'],
      climateInfo: {'Sıcaklık': '-30-28°C', 'Yağış': '450-550mm/yıl', 'Nem': 'Orta', 'Rüzgar': 'Sert'},
    ),
    CityData(
      name: 'Kastamonu',
      region: 'Karadeniz',
      climate: 'Karadeniz-Karasal Geçiş',
      soilType: 'Killi-Tınlı Toprak',
      suitableCrops: ['Sarımsak', 'Siyez Buğdayı', 'Şeker Pancarı', 'Mısır', 'Elma'],
      climateInfo: {'Sıcaklık': '-8-32°C', 'Yağış': '500-800mm/yıl', 'Nem': 'Orta', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Kayseri',
      region: 'İç Anadolu',
      climate: 'Karasal',
      soilType: 'Killi Toprak',
      suitableCrops: ['Buğday', 'Arpa', 'Mısır', 'Ayçiçeği', 'Şeker Pancarı', 'Patates', 'Soğan', 'Havuç', 'Elma'],
      climateInfo: {'Sıcaklık': '-10-35°C', 'Yağış': '350-450mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Yüksek'},
    ),
    CityData(
      name: 'Kırıkkale',
      region: 'İç Anadolu',
      climate: 'Karasal',
      soilType: 'Killi Toprak',
      suitableCrops: ['Buğday', 'Arpa', 'Mısır', 'Ayçiçeği', 'Şeker Pancarı', 'Patates', 'Soğan', 'Havuç'],
      climateInfo: {'Sıcaklık': '-8-36°C', 'Yağış': '400-500mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Yüksek'},
    ),
    CityData(
      name: 'Kırklareli',
      region: 'Marmara',
      climate: 'Akdeniz-Karadeniz Geçiş',
      soilType: 'Kumlu-Killi Toprak',
      suitableCrops: ['Ayçiçeği', 'Buğday', 'Arpa', 'Mısır', 'Domates', 'Biber', 'Patlıcan', 'Kabak'],
      climateInfo: {'Sıcaklık': '0-30°C', 'Yağış': '550-650mm/yıl', 'Nem': 'Orta', 'Rüzgar': 'Yüksek'},
    ),
    CityData(
      name: 'Kırşehir',
      region: 'İç Anadolu',
      climate: 'Karasal',
      soilType: 'Killi Toprak',
      suitableCrops: ['Buğday', 'Arpa', 'Mısır', 'Ayçiçeği', 'Şeker Pancarı', 'Patates', 'Soğan', 'Havuç'],
      climateInfo: {'Sıcaklık': '-8-36°C', 'Yağış': '400-500mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Yüksek'},
    ),
    CityData(
      name: 'Kilis',
      region: 'Güneydoğu Anadolu',
      climate: 'Karasal-Akdeniz Geçiş',
      soilType: 'Killi-Kumlu Toprak',
      suitableCrops: ['Zeytin', 'Üzüm', 'Domates', 'Biber', 'Patlıcan', 'Kabak', 'Salatalık', 'Marul'],
      climateInfo: {'Sıcaklık': '2-40°C', 'Yağış': '500-600mm/yıl', 'Nem': 'Orta', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Kocaeli',
      region: 'Marmara',
      climate: 'Akdeniz-Karadeniz Geçiş',
      soilType: 'Killi-Tınlı Toprak',
      suitableCrops: ['Domates', 'Biber', 'Patlıcan', 'Salatalık', 'Marul', 'Ispanak', 'Maydanoz', 'Fesleğen'],
      climateInfo: {'Sıcaklık': '5-30°C', 'Yağış': '700-800mm/yıl', 'Nem': 'Yüksek', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Konya',
      region: 'İç Anadolu',
      climate: 'Karasal',
      soilType: 'Killi-Tuzlu Toprak',
      suitableCrops: ['Buğday', 'Arpa', 'Şeker Pancarı', 'Ayçiçeği', 'Mısır', 'Patates', 'Soğan', 'Havuç'],
      climateInfo: {'Sıcaklık': '-8-38°C', 'Yağış': '300-400mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Yüksek'},
    ),
    CityData(
      name: 'Kütahya',
      region: 'Ege',
      climate: 'Karasal',
      soilType: 'Killi Toprak',
      suitableCrops: ['Buğday', 'Arpa', 'Mısır', 'Ayçiçeği', 'Şeker Pancarı', 'Patates', 'Soğan', 'Havuç'],
      climateInfo: {'Sıcaklık': '-8-35°C', 'Yağış': '450-550mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Yüksek'},
    ),
    CityData(
      name: 'Malatya',
      region: 'Doğu Anadolu',
      climate: 'Karasal',
      soilType: 'Killi-Kumlu Toprak',
      suitableCrops: ['Kayısı', 'Buğday', 'Arpa', 'Mısır', 'Ayçiçeği', 'Patates', 'Soğan', 'Havuç', 'Elma'],
      climateInfo: {'Sıcaklık': '-12-38°C', 'Yağış': '350-450mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Yüksek'},
    ),
    CityData(
      name: 'Manisa',
      region: 'Ege',
      climate: 'Akdeniz',
      soilType: 'Kumlu-Killi Toprak',
      suitableCrops: ['Üzüm', 'Zeytin', 'İncir', 'Nar', 'Turunçgil', 'Domates', 'Biber', 'Patlıcan', 'Kabak'],
      climateInfo: {'Sıcaklık': '6-34°C', 'Yağış': '500-600mm/yıl', 'Nem': 'Orta', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Mardin',
      region: 'Güneydoğu Anadolu',
      climate: 'Karasal-Akdeniz Geçiş',
      soilType: 'Killi-Kumlu Toprak',
      suitableCrops: ['Antep Fıstığı', 'Üzüm', 'Zeytin', 'Domates', 'Biber', 'Patlıcan', 'Kabak', 'Salatalık'],
      climateInfo: {'Sıcaklık': '-2-40°C', 'Yağış': '450-550mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Mersin',
      region: 'Akdeniz',
      climate: 'Akdeniz',
      soilType: 'Kumlu-Killi Toprak',
      suitableCrops: ['Turunçgil', 'Avokado', 'Mango', 'Domates', 'Biber', 'Patlıcan', 'Kabak', 'Salatalık', 'Marul'],
      climateInfo: {'Sıcaklık': '10-38°C', 'Yağış': '700-900mm/yıl', 'Nem': 'Yüksek', 'Rüzgar': 'Düşük'},
    ),
    CityData(
      name: 'Muğla',
      region: 'Ege',
      climate: 'Akdeniz',
      soilType: 'Kumlu-Killi Toprak',
      suitableCrops: ['Zeytin', 'Üzüm', 'İncir', 'Nar', 'Turunçgil', 'Domates', 'Biber', 'Patlıcan'],
      climateInfo: {'Sıcaklık': '8-35°C', 'Yağış': '600-700mm/yıl', 'Nem': 'Orta', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Muş',
      region: 'Doğu Anadolu',
      climate: 'Karasal',
      soilType: 'Killi-Asitli Toprak',
      suitableCrops: ['Buğday', 'Arpa', 'Patates', 'Lahana', 'Havuç', 'Soğan', 'Ispanak', 'Maydanoz'],
      climateInfo: {'Sıcaklık': '-18-32°C', 'Yağış': '500-600mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Yüksek'},
    ),
    CityData(
      name: 'Nevşehir',
      region: 'İç Anadolu',
      climate: 'Karasal',
      soilType: 'Killi-Tuzlu Toprak',
      suitableCrops: ['Buğday', 'Arpa', 'Mısır', 'Ayçiçeği', 'Şeker Pancarı', 'Patates', 'Soğan', 'Havuç'],
      climateInfo: {'Sıcaklık': '-8-36°C', 'Yağış': '350-450mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Yüksek'},
    ),
    CityData(
      name: 'Niğde',
      region: 'İç Anadolu',
      climate: 'Karasal',
      soilType: 'Killi-Tuzlu Toprak',
      suitableCrops: ['Buğday', 'Arpa', 'Mısır', 'Ayçiçeği', 'Şeker Pancarı', 'Patates', 'Soğan', 'Havuç'],
      climateInfo: {'Sıcaklık': '-10-36°C', 'Yağış': '350-450mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Yüksek'},
    ),
    CityData(
      name: 'Ordu',
      region: 'Karadeniz',
      climate: 'Karadeniz',
      soilType: 'Asitli-Killi Toprak',
      suitableCrops: ['Fındık', 'Çay', 'Mısır', 'Fasulye', 'Lahana', 'Karnabahar', 'Brokoli', 'Ispanak', 'Maydanoz'],
      climateInfo: {'Sıcaklık': '5-27°C', 'Yağış': '1000-1300mm/yıl', 'Nem': 'Çok Yüksek', 'Rüzgar': 'Düşük'},
    ),
    CityData(
      name: 'Osmaniye',
      region: 'Akdeniz',
      climate: 'Akdeniz',
      soilType: 'Kumlu-Killi Toprak',
      suitableCrops: ['Turunçgil', 'Domates', 'Biber', 'Patlıcan', 'Kabak', 'Salatalık', 'Marul', 'Ispanak'],
      climateInfo: {'Sıcaklık': '5-38°C', 'Yağış': '600-800mm/yıl', 'Nem': 'Yüksek', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Rize',
      region: 'Karadeniz',
      climate: 'Karadeniz',
      soilType: 'Asitli-Killi Toprak',
      suitableCrops: ['Çay', 'Fındık', 'Mısır', 'Fasulye', 'Lahana', 'Karnabahar', 'Brokoli', 'Ispanak', 'Maydanoz'],
      climateInfo: {'Sıcaklık': '4-26°C', 'Yağış': '1400-1800mm/yıl', 'Nem': 'Çok Yüksek', 'Rüzgar': 'Düşük'},
    ),
    CityData(
      name: 'Sakarya',
      region: 'Marmara',
      climate: 'Akdeniz-Karadeniz Geçiş',
      soilType: 'Killi-Tınlı Toprak',
      suitableCrops: ['Fındık', 'Elma', 'Armut', 'Şeftali', 'Domates', 'Biber', 'Patlıcan', 'Salatalık'],
      climateInfo: {'Sıcaklık': '3-30°C', 'Yağış': '700-800mm/yıl', 'Nem': 'Yüksek', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Samsun',
      region: 'Karadeniz',
      climate: 'Karadeniz',
      soilType: 'Killi-Asitli Toprak',
      suitableCrops: ['Tütün', 'Mısır', 'Fasulye', 'Lahana', 'Karnabahar', 'Brokoli', 'Ispanak', 'Maydanoz'],
      climateInfo: {'Sıcaklık': '3-28°C', 'Yağış': '700-900mm/yıl', 'Nem': 'Yüksek', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Siirt',
      region: 'Güneydoğu Anadolu',
      climate: 'Karasal-Akdeniz Geçiş',
      soilType: 'Killi-Kumlu Toprak',
      suitableCrops: ['Antep Fıstığı', 'Üzüm', 'Zeytin', 'Domates', 'Biber', 'Patlıcan', 'Kabak', 'Salatalık'],
      climateInfo: {'Sıcaklık': '-5-40°C', 'Yağış': '500-600mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Sinop',
      region: 'Karadeniz',
      climate: 'Karadeniz',
      soilType: 'Killi-Asitli Toprak',
      suitableCrops: ['Fındık', 'Mısır', 'Fasulye', 'Lahana', 'Karnabahar', 'Brokoli', 'Ispanak', 'Maydanoz'],
      climateInfo: {'Sıcaklık': '2-26°C', 'Yağış': '700-900mm/yıl', 'Nem': 'Yüksek', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Sivas',
      region: 'İç Anadolu',
      climate: 'Karasal',
      soilType: 'Killi-Asitli Toprak',
      suitableCrops: ['Buğday', 'Arpa', 'Patates', 'Lahana', 'Havuç', 'Soğan', 'Ispanak', 'Maydanoz', 'Elma'],
      climateInfo: {'Sıcaklık': '-15-32°C', 'Yağış': '400-500mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Yüksek'},
    ),
    CityData(
      name: 'Şanlıurfa',
      region: 'Güneydoğu Anadolu',
      climate: 'Karasal-Akdeniz Geçiş',
      soilType: 'Killi-Kumlu Toprak',
      suitableCrops: ['Antep Fıstığı', 'Üzüm', 'Zeytin', 'Domates', 'Biber', 'Patlıcan', 'Kabak', 'Salatalık', 'Pamuk'],
      climateInfo: {'Sıcaklık': '0-45°C', 'Yağış': '400-500mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Şırnak',
      region: 'Güneydoğu Anadolu',
      climate: 'Karasal-Akdeniz Geçiş',
      soilType: 'Killi-Kumlu Toprak',
      suitableCrops: ['Antep Fıstığı', 'Üzüm', 'Zeytin', 'Domates', 'Biber', 'Patlıcan', 'Kabak', 'Salatalık'],
      climateInfo: {'Sıcaklık': '-5-40°C', 'Yağış': '500-600mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Tekirdağ',
      region: 'Marmara',
      climate: 'Akdeniz-Karadeniz Geçiş',
      soilType: 'Kumlu-Killi Toprak',
      suitableCrops: ['Üzüm', 'Ayçiçeği', 'Buğday', 'Arpa', 'Mısır', 'Domates', 'Biber', 'Patlıcan', 'Kabak'],
      climateInfo: {'Sıcaklık': '5-29°C', 'Yağış': '600-700mm/yıl', 'Nem': 'Orta', 'Rüzgar': 'Yüksek'},
    ),
    CityData(
      name: 'Tokat',
      region: 'Karadeniz',
      climate: 'Karadeniz-Karasal Geçiş',
      soilType: 'Killi-Tınlı Toprak',
      suitableCrops: ['Elma', 'Armut', 'Şeftali', 'Kiraz', 'Domates', 'Biber', 'Patlıcan', 'Salatalık'],
      climateInfo: {'Sıcaklık': '-5-35°C', 'Yağış': '500-600mm/yıl', 'Nem': 'Orta', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Trabzon',
      region: 'Karadeniz',
      climate: 'Karadeniz',
      soilType: 'Asitli-Killi Toprak',
      suitableCrops: ['Çay', 'Fındık', 'Mısır', 'Fasulye', 'Lahana', 'Karnabahar', 'Brokoli', 'Ispanak'],
      climateInfo: {'Sıcaklık': '5-25°C', 'Yağış': '1200-1500mm/yıl', 'Nem': 'Çok Yüksek', 'Rüzgar': 'Düşük'},
    ),
    CityData(
      name: 'Tunceli',
      region: 'Doğu Anadolu',
      climate: 'Karasal',
      soilType: 'Killi-Asitli Toprak',
      suitableCrops: ['Buğday', 'Arpa', 'Patates', 'Lahana', 'Havuç', 'Soğan', 'Ispanak', 'Maydanoz'],
      climateInfo: {'Sıcaklık': '-15-32°C', 'Yağış': '500-600mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Yüksek'},
    ),
    CityData(
      name: 'Uşak',
      region: 'Ege',
      climate: 'Akdeniz-Karasal Geçiş',
      soilType: 'Killi-Kumlu Toprak',
      suitableCrops: ['Üzüm', 'Elma', 'Armut', 'Şeftali', 'Domates', 'Biber', 'Patlıcan', 'Salatalık'],
      climateInfo: {'Sıcaklık': '-5-36°C', 'Yağış': '450-550mm/yıl', 'Nem': 'Düşük-Orta', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Van',
      region: 'Doğu Anadolu',
      climate: 'Karasal',
      soilType: 'Killi-Asitli Toprak',
      suitableCrops: ['Buğday', 'Arpa', 'Patates', 'Lahana', 'Havuç', 'Soğan', 'Ispanak', 'Maydanoz', 'Elma'],
      climateInfo: {'Sıcaklık': '-20-28°C', 'Yağış': '400-500mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Yüksek'},
    ),
    CityData(
      name: 'Yalova',
      region: 'Marmara',
      climate: 'Akdeniz-Karadeniz Geçiş',
      soilType: 'Killi-Tınlı Toprak',
      suitableCrops: ['Domates', 'Biber', 'Patlıcan', 'Salatalık', 'Marul', 'Ispanak', 'Maydanoz', 'Fesleğen'],
      climateInfo: {'Sıcaklık': '5-30°C', 'Yağış': '700-800mm/yıl', 'Nem': 'Yüksek', 'Rüzgar': 'Orta'},
    ),
    CityData(
      name: 'Yozgat',
      region: 'İç Anadolu',
      climate: 'Karasal',
      soilType: 'Killi Toprak',
      suitableCrops: ['Buğday', 'Arpa', 'Mısır', 'Ayçiçeği', 'Şeker Pancarı', 'Patates', 'Soğan', 'Havuç'],
      climateInfo: {'Sıcaklık': '-10-35°C', 'Yağış': '400-500mm/yıl', 'Nem': 'Düşük', 'Rüzgar': 'Yüksek'},
    ),
    CityData(
      name: 'Zonguldak',
      region: 'Karadeniz',
      climate: 'Karadeniz',
      soilType: 'Killi-Asitli Toprak',
      suitableCrops: ['Fındık', 'Mısır', 'Fasulye', 'Lahana', 'Karnabahar', 'Brokoli', 'Ispanak', 'Maydanoz'],
      climateInfo: {'Sıcaklık': '3-28°C', 'Yağış': '1000-1200mm/yıl', 'Nem': 'Yüksek', 'Rüzgar': 'Orta'},
    ),
  ];

  static List<CityData> getTurkishCities() {
    return _cities;
  }
}
