class CropGuide {
  final String name;
  final String plantingSeason;
  final String plantingMethod;
  final String wateringSchedule;
  final String wateringAmount;
  final String soilRequirements;
  final String harvestTime;
  final String careTips;
  final List<String> commonProblems;
  final Map<String, String> detailedInfo;

  CropGuide({
    required this.name,
    required this.plantingSeason,
    required this.plantingMethod,
    required this.wateringSchedule,
    required this.wateringAmount,
    required this.soilRequirements,
    required this.harvestTime,
    required this.careTips,
    required this.commonProblems,
    required this.detailedInfo,
  });

  static Map<String, CropGuide> getCropGuides() {
    return {
      'Domates': CropGuide(
        name: 'Domates',
        plantingSeason: 'Mart-Nisan (Sera: Şubat)',
        plantingMethod: 'Fide dikimi, 50-60cm aralık',
        wateringSchedule: 'Her 2-3 günde bir',
        wateringAmount: '5-7 litre/m²',
        soilRequirements: 'pH 6.0-6.8, iyi drenajlı toprak',
        harvestTime: 'Ekimden 75-90 gün sonra',
        careTips: 'Destek çubuğu kullanın, yan sürgünleri temizleyin',
        commonProblems: ['Yaprak sararması', 'Çiçek dökümü', 'Meyve çatlaması'],
        detailedInfo: {
          'Ekim Derinliği': '2-3 cm',
          'Sıcaklık': '18-25°C (gündüz), 15-18°C (gece)',
          'Gübreleme': 'Azot, fosfor, potasyum dengesi',
          'Hastalık': 'Mildiyö, bakteriyel leke',
          'Zararlı': 'Beyaz sinek, kırmızı örümcek'
        },
      ),
      'Biber': CropGuide(
        name: 'Biber',
        plantingSeason: 'Nisan-Mayıs',
        plantingMethod: 'Fide dikimi, 40-50cm aralık',
        wateringSchedule: 'Her 2-3 günde bir',
        wateringAmount: '4-6 litre/m²',
        soilRequirements: 'pH 6.0-7.0, organik madde açısından zengin',
        harvestTime: 'Ekimden 60-80 gün sonra',
        careTips: 'Düzenli sulama, güneşli yer seçin',
        commonProblems: ['Meyve dökümü', 'Yaprak sararması', 'Büyüme durması'],
        detailedInfo: {
          'Ekim Derinliği': '1-2 cm',
          'Sıcaklık': '20-30°C (gündüz), 15-20°C (gece)',
          'Gübreleme': 'Kompost, organik gübre',
          'Hastalık': 'Antraknoz, bakteriyel leke',
          'Zararlı': 'Thrips, yaprak biti'
        },
      ),
      'Buğday': CropGuide(
        name: 'Buğday',
        plantingSeason: 'Ekim-Kasım (Sonbahar)',
        plantingMethod: 'Tohum ekimi, 15-20cm sıra arası',
        wateringSchedule: 'Yağışa bağlı, kurak dönemde sulama',
        wateringAmount: '300-400mm/mevsim',
        soilRequirements: 'pH 6.0-7.5, iyi drenajlı toprak',
        harvestTime: 'Haziran-Temmuz',
        careTips: 'Düzenli toprak işleme, yabani ot temizliği',
        commonProblems: ['Pas hastalığı', 'Kök çürüklüğü', 'Yabani ot'],
        detailedInfo: {
          'Ekim Derinliği': '2-4 cm',
          'Sıcaklık': '15-25°C (büyüme), 20-30°C (olgunlaşma)',
          'Gübreleme': 'Azot, fosfor, potasyum',
          'Hastalık': 'Pas, septoria, fusarium',
          'Zararlı': 'Süne, kımıl'
        },
      ),
      'Mısır': CropGuide(
        name: 'Mısır',
        plantingSeason: 'Nisan-Mayıs',
        plantingMethod: 'Tohum ekimi, 70-80cm sıra arası',
        wateringSchedule: 'Her 5-7 günde bir',
        wateringAmount: '6-8 litre/m²',
        soilRequirements: 'pH 6.0-7.0, derin toprak',
        harvestTime: 'Ekimden 90-120 gün sonra',
        careTips: 'Yüksek sıcaklık sever, düzenli sulama',
        commonProblems: ['Kök çürüklüğü', 'Yaprak hastalığı', 'Zararlı böcek'],
        detailedInfo: {
          'Ekim Derinliği': '3-5 cm',
          'Sıcaklık': '20-30°C (büyüme), 25-35°C (olgunlaşma)',
          'Gübreleme': 'Azot ağırlıklı gübreleme',
          'Hastalık': 'Helminthosporium, rust',
          'Zararlı': 'Mısır kurdu, yaprak biti'
        },
      ),
      'Patates': CropGuide(
        name: 'Patates',
        plantingSeason: 'Mart-Nisan',
        plantingMethod: 'Yumru dikimi, 30-40cm aralık',
        wateringSchedule: 'Her 3-4 günde bir',
        wateringAmount: '5-7 litre/m²',
        soilRequirements: 'pH 5.0-6.5, gevşek toprak',
        harvestTime: 'Ekimden 90-120 gün sonra',
        careTips: 'Hilling yapın, düzenli sulama',
        commonProblems: ['Yumru çürüklüğü', 'Yaprak hastalığı', 'Zararlı böcek'],
        detailedInfo: {
          'Ekim Derinliği': '8-12 cm',
          'Sıcaklık': '15-25°C (büyüme), 10-20°C (yumru)',
          'Gübreleme': 'Potasyum ağırlıklı',
          'Hastalık': 'Late blight, early blight',
          'Zararlı': 'Colorado böceği, nematod'
        },
      ),
      'Salatalık': CropGuide(
        name: 'Salatalık',
        plantingSeason: 'Nisan-Mayıs',
        plantingMethod: 'Tohum ekimi, 50-60cm aralık',
        wateringSchedule: 'Her 2-3 günde bir',
        wateringAmount: '4-6 litre/m²',
        soilRequirements: 'pH 6.0-7.0, organik madde açısından zengin',
        harvestTime: 'Ekimden 50-70 gün sonra',
        careTips: 'Destek sistemi kullanın, düzenli hasat',
        commonProblems: ['Meyve acılaşması', 'Yaprak sararması', 'Çiçek dökümü'],
        detailedInfo: {
          'Ekim Derinliği': '2-3 cm',
          'Sıcaklık': '20-30°C (gündüz), 15-20°C (gece)',
          'Gübreleme': 'Azot, fosfor, potasyum',
          'Hastalık': 'Mildiyö, bakteriyel leke',
          'Zararlı': 'Beyaz sinek, kırmızı örümcek'
        },
      ),
      'Marul': CropGuide(
        name: 'Marul',
        plantingSeason: 'Şubat-Ekim (sera: yıl boyu)',
        plantingMethod: 'Fide dikimi, 25-30cm aralık',
        wateringSchedule: 'Her 2-3 günde bir',
        wateringAmount: '3-4 litre/m²',
        soilRequirements: 'pH 6.0-7.0, organik madde açısından zengin',
        harvestTime: 'Ekimden 45-60 gün sonra',
        careTips: 'Serin hava sever, düzenli sulama',
        commonProblems: ['Yaprak yanıklığı', 'Kök çürüklüğü', 'Zararlı böcek'],
        detailedInfo: {
          'Ekim Derinliği': '0.5-1 cm',
          'Sıcaklık': '15-20°C (gündüz), 10-15°C (gece)',
          'Gübreleme': 'Azot ağırlıklı',
          'Hastalık': 'Sclerotinia, bakteriyel leke',
          'Zararlı': 'Yaprak biti, salyangoz'
        },
      ),
      'Ispanak': CropGuide(
        name: 'Ispanak',
        plantingSeason: 'Eylül-Mart',
        plantingMethod: 'Tohum ekimi, 20-25cm sıra arası',
        wateringSchedule: 'Her 2-3 günde bir',
        wateringAmount: '3-4 litre/m²',
        soilRequirements: 'pH 6.0-7.5, organik madde açısından zengin',
        harvestTime: 'Ekimden 30-45 gün sonra',
        careTips: 'Serin hava sever, düzenli sulama',
        commonProblems: ['Yaprak sararması', 'Kök çürüklüğü', 'Zararlı böcek'],
        detailedInfo: {
          'Ekim Derinliği': '1-2 cm',
          'Sıcaklık': '10-20°C (gündüz), 5-15°C (gece)',
          'Gübreleme': 'Azot ağırlıklı',
          'Hastalık': 'Mildiyö, bakteriyel leke',
          'Zararlı': 'Yaprak biti, salyangoz'
        },
      ),
      // Yeni Eklenen Mahsuller
      'Patlıcan': CropGuide(
        name: 'Patlıcan',
        plantingSeason: 'Nisan-Mayıs',
        plantingMethod: 'Fide dikimi, 50-60cm aralık',
        wateringSchedule: 'Her 2-3 günde bir',
        wateringAmount: '5-7 litre/m²',
        soilRequirements: 'pH 6.0-7.0, organik madde açısından zengin',
        harvestTime: 'Ekimden 70-90 gün sonra',
        careTips: 'Destek çubuğu kullanın, düzenli sulama',
        commonProblems: ['Meyve dökümü', 'Yaprak sararması', 'Büyüme durması'],
        detailedInfo: {
          'Ekim Derinliği': '1-2 cm',
          'Sıcaklık': '20-30°C (gündüz), 15-20°C (gece)',
          'Gübreleme': 'Azot, fosfor, potasyum',
          'Hastalık': 'Verticillium, bakteriyel leke',
          'Zararlı': 'Beyaz sinek, kırmızı örümcek'
        },
      ),
      'Kabak': CropGuide(
        name: 'Kabak',
        plantingSeason: 'Nisan-Mayıs',
        plantingMethod: 'Tohum ekimi, 80-100cm aralık',
        wateringSchedule: 'Her 3-4 günde bir',
        wateringAmount: '6-8 litre/m²',
        soilRequirements: 'pH 6.0-7.0, organik madde açısından zengin',
        harvestTime: 'Ekimden 50-70 gün sonra',
        careTips: 'Geniş alan gerektirir, düzenli hasat',
        commonProblems: ['Meyve çürüklüğü', 'Yaprak sararması', 'Zararlı böcek'],
        detailedInfo: {
          'Ekim Derinliği': '2-3 cm',
          'Sıcaklık': '20-30°C (gündüz), 15-20°C (gece)',
          'Gübreleme': 'Azot, fosfor, potasyum',
          'Hastalık': 'Mildiyö, bakteriyel leke',
          'Zararlı': 'Kabak böceği, yaprak biti'
        },
      ),
      'Maydanoz': CropGuide(
        name: 'Maydanoz',
        plantingSeason: 'Mart-Ekim',
        plantingMethod: 'Tohum ekimi, 15-20cm sıra arası',
        wateringSchedule: 'Her 2-3 günde bir',
        wateringAmount: '2-3 litre/m²',
        soilRequirements: 'pH 6.0-7.0, organik madde açısından zengin',
        harvestTime: 'Ekimden 60-80 gün sonra',
        careTips: 'Serin hava sever, düzenli sulama',
        commonProblems: ['Yaprak sararması', 'Kök çürüklüğü', 'Zararlı böcek'],
        detailedInfo: {
          'Ekim Derinliği': '0.5-1 cm',
          'Sıcaklık': '15-25°C (gündüz), 10-15°C (gece)',
          'Gübreleme': 'Azot ağırlıklı',
          'Hastalık': 'Mildiyö, bakteriyel leke',
          'Zararlı': 'Yaprak biti, salyangoz'
        },
      ),
      'Fesleğen': CropGuide(
        name: 'Fesleğen',
        plantingSeason: 'Nisan-Mayıs',
        plantingMethod: 'Fide dikimi, 25-30cm aralık',
        wateringSchedule: 'Her 2-3 günde bir',
        wateringAmount: '3-4 litre/m²',
        soilRequirements: 'pH 6.0-7.0, organik madde açısından zengin',
        harvestTime: 'Ekimden 60-80 gün sonra',
        careTips: 'Güneşli yer seçin, düzenli budama',
        commonProblems: ['Yaprak sararması', 'Kök çürüklüğü', 'Zararlı böcek'],
        detailedInfo: {
          'Ekim Derinliği': '0.5-1 cm',
          'Sıcaklık': '20-30°C (gündüz), 15-20°C (gece)',
          'Gübreleme': 'Azot ağırlıklı',
          'Hastalık': 'Mildiyö, bakteriyel leke',
          'Zararlı': 'Yaprak biti, beyaz sinek'
        },
      ),
      'Arpa': CropGuide(
        name: 'Arpa',
        plantingSeason: 'Ekim-Kasım (Sonbahar)',
        plantingMethod: 'Tohum ekimi, 15-20cm sıra arası',
        wateringSchedule: 'Yağışa bağlı, kurak dönemde sulama',
        wateringAmount: '250-350mm/mevsim',
        soilRequirements: 'pH 6.0-7.5, iyi drenajlı toprak',
        harvestTime: 'Haziran-Temmuz',
        careTips: 'Düzenli toprak işleme, yabani ot temizliği',
        commonProblems: ['Pas hastalığı', 'Kök çürüklüğü', 'Yabani ot'],
        detailedInfo: {
          'Ekim Derinliği': '2-4 cm',
          'Sıcaklık': '15-25°C (büyüme), 20-30°C (olgunlaşma)',
          'Gübreleme': 'Azot, fosfor, potasyum',
          'Hastalık': 'Pas, septoria, fusarium',
          'Zararlı': 'Süne, kımıl'
        },
      ),
      'Ayçiçeği': CropGuide(
        name: 'Ayçiçeği',
        plantingSeason: 'Nisan-Mayıs',
        plantingMethod: 'Tohum ekimi, 70-80cm sıra arası',
        wateringSchedule: 'Her 5-7 günde bir',
        wateringAmount: '6-8 litre/m²',
        soilRequirements: 'pH 6.0-7.5, derin toprak',
        harvestTime: 'Ekimden 90-120 gün sonra',
        careTips: 'Güneşli yer seçin, düzenli sulama',
        commonProblems: ['Kök çürüklüğü', 'Yaprak hastalığı', 'Zararlı böcek'],
        detailedInfo: {
          'Ekim Derinliği': '3-5 cm',
          'Sıcaklık': '20-30°C (büyüme), 25-35°C (olgunlaşma)',
          'Gübreleme': 'Azot, fosfor, potasyum',
          'Hastalık': 'Helminthosporium, rust',
          'Zararlı': 'Ayçiçeği kurdu, yaprak biti'
        },
      ),
      'Şeker Pancarı': CropGuide(
        name: 'Şeker Pancarı',
        plantingSeason: 'Mart-Nisan',
        plantingMethod: 'Tohum ekimi, 45-50cm sıra arası',
        wateringSchedule: 'Her 5-7 günde bir',
        wateringAmount: '8-10 litre/m²',
        soilRequirements: 'pH 6.0-7.5, derin toprak',
        harvestTime: 'Ekimden 150-180 gün sonra',
        careTips: 'Düzenli toprak işleme, yabani ot temizliği',
        commonProblems: ['Kök çürüklüğü', 'Yaprak hastalığı', 'Zararlı böcek'],
        detailedInfo: {
          'Ekim Derinliği': '2-3 cm',
          'Sıcaklık': '15-25°C (büyüme), 20-30°C (olgunlaşma)',
          'Gübreleme': 'Azot, fosfor, potasyum',
          'Hastalık': 'Cercospora, bakteriyel leke',
          'Zararlı': 'Şeker pancarı kurdu, yaprak biti'
        },
      ),
      'Soğan': CropGuide(
        name: 'Soğan',
        plantingSeason: 'Ekim-Mart',
        plantingMethod: 'Tohum ekimi, 25-30cm sıra arası',
        wateringSchedule: 'Her 3-4 günde bir',
        wateringAmount: '4-6 litre/m²',
        soilRequirements: 'pH 6.0-7.0, organik madde açısından zengin',
        harvestTime: 'Ekimden 120-150 gün sonra',
        careTips: 'Düzenli sulama, yabani ot temizliği',
        commonProblems: ['Kök çürüklüğü', 'Yaprak hastalığı', 'Zararlı böcek'],
        detailedInfo: {
          'Ekim Derinliği': '1-2 cm',
          'Sıcaklık': '15-25°C (büyüme), 20-30°C (olgunlaşma)',
          'Gübreleme': 'Azot, fosfor, potasyum',
          'Hastalık': 'Mildiyö, bakteriyel leke',
          'Zararlı': 'Soğan sineği, yaprak biti'
        },
      ),
      'Havuç': CropGuide(
        name: 'Havuç',
        plantingSeason: 'Mart-Ekim',
        plantingMethod: 'Tohum ekimi, 25-30cm sıra arası',
        wateringSchedule: 'Her 3-4 günde bir',
        wateringAmount: '4-6 litre/m²',
        soilRequirements: 'pH 6.0-7.0, gevşek toprak',
        harvestTime: 'Ekimden 70-90 gün sonra',
        careTips: 'Gevşek toprak gerektirir, düzenli sulama',
        commonProblems: ['Kök çürüklüğü', 'Yaprak hastalığı', 'Zararlı böcek'],
        detailedInfo: {
          'Ekim Derinliği': '1-2 cm',
          'Sıcaklık': '15-25°C (büyüme), 20-30°C (olgunlaşma)',
          'Gübreleme': 'Azot, fosfor, potasyum',
          'Hastalık': 'Mildiyö, bakteriyel leke',
          'Zararlı': 'Havuç sineği, yaprak biti'
        },
      ),
      'Zeytin': CropGuide(
        name: 'Zeytin',
        plantingSeason: 'Ekim-Mart',
        plantingMethod: 'Fide dikimi, 6-8m aralık',
        wateringSchedule: 'Her 10-15 günde bir',
        wateringAmount: '20-30 litre/ağaç',
        soilRequirements: 'pH 6.0-8.0, iyi drenajlı toprak',
        harvestTime: 'Ekimden 3-4 yıl sonra',
        careTips: 'Düzenli budama, güneşli yer seçin',
        commonProblems: ['Kök çürüklüğü', 'Yaprak hastalığı', 'Zararlı böcek'],
        detailedInfo: {
          'Ekim Derinliği': '50-60 cm',
          'Sıcaklık': '15-30°C (büyüme), 20-35°C (olgunlaşma)',
          'Gübreleme': 'Azot, fosfor, potasyum',
          'Hastalık': 'Verticillium, bakteriyel leke',
          'Zararlı': 'Zeytin sineği, yaprak biti'
        },
      ),
      'Üzüm': CropGuide(
        name: 'Üzüm',
        plantingSeason: 'Ekim-Mart',
        plantingMethod: 'Fide dikimi, 2-3m aralık',
        wateringSchedule: 'Her 7-10 günde bir',
        wateringAmount: '15-20 litre/ağaç',
        soilRequirements: 'pH 6.0-7.5, iyi drenajlı toprak',
        harvestTime: 'Ekimden 2-3 yıl sonra',
        careTips: 'Destek sistemi kullanın, düzenli budama',
        commonProblems: ['Kök çürüklüğü', 'Yaprak hastalığı', 'Zararlı böcek'],
        detailedInfo: {
          'Ekim Derinliği': '40-50 cm',
          'Sıcaklık': '15-30°C (büyüme), 20-35°C (olgunlaşma)',
          'Gübreleme': 'Azot, fosfor, potasyum',
          'Hastalık': 'Mildiyö, bakteriyel leke',
          'Zararlı': 'Üzüm kurdu, yaprak biti'
        },
      ),
      'İncir': CropGuide(
        name: 'İncir',
        plantingSeason: 'Ekim-Mart',
        plantingMethod: 'Fide dikimi, 4-5m aralık',
        wateringSchedule: 'Her 10-15 günde bir',
        wateringAmount: '15-20 litre/ağaç',
        soilRequirements: 'pH 6.0-8.0, iyi drenajlı toprak',
        harvestTime: 'Ekimden 2-3 yıl sonra',
        careTips: 'Güneşli yer seçin, düzenli budama',
        commonProblems: ['Kök çürüklüğü', 'Yaprak hastalığı', 'Zararlı böcek'],
        detailedInfo: {
          'Ekim Derinliği': '50-60 cm',
          'Sıcaklık': '15-30°C (büyüme), 20-35°C (olgunlaşma)',
          'Gübreleme': 'Azot, fosfor, potasyum',
          'Hastalık': 'Verticillium, bakteriyel leke',
          'Zararlı': 'İncir sineği, yaprak biti'
        },
      ),
      'Nar': CropGuide(
        name: 'Nar',
        plantingSeason: 'Ekim-Mart',
        plantingMethod: 'Fide dikimi, 3-4m aralık',
        wateringSchedule: 'Her 10-15 günde bir',
        wateringAmount: '15-20 litre/ağaç',
        soilRequirements: 'pH 6.0-8.0, iyi drenajlı toprak',
        harvestTime: 'Ekimden 2-3 yıl sonra',
        careTips: 'Güneşli yer seçin, düzenli budama',
        commonProblems: ['Kök çürüklüğü', 'Yaprak hastalığı', 'Zararlı böcek'],
        detailedInfo: {
          'Ekim Derinliği': '50-60 cm',
          'Sıcaklık': '15-30°C (büyüme), 20-35°C (olgunlaşma)',
          'Gübreleme': 'Azot, fosfor, potasyum',
          'Hastalık': 'Verticillium, bakteriyel leke',
          'Zararlı': 'Nar sineği, yaprak biti'
        },
      ),
      'Turunçgil': CropGuide(
        name: 'Turunçgil',
        plantingSeason: 'Ekim-Mart',
        plantingMethod: 'Fide dikimi, 4-5m aralık',
        wateringSchedule: 'Her 7-10 günde bir',
        wateringAmount: '20-25 litre/ağaç',
        soilRequirements: 'pH 6.0-7.5, iyi drenajlı toprak',
        harvestTime: 'Ekimden 3-4 yıl sonra',
        careTips: 'Güneşli yer seçin, düzenli budama',
        commonProblems: ['Kök çürüklüğü', 'Yaprak hastalığı', 'Zararlı böcek'],
        detailedInfo: {
          'Ekim Derinliği': '50-60 cm',
          'Sıcaklık': '15-30°C (büyüme), 20-35°C (olgunlaşma)',
          'Gübreleme': 'Azot, fosfor, potasyum',
          'Hastalık': 'Verticillium, bakteriyel leke',
          'Zararlı': 'Turunçgil sineği, yaprak biti'
        },
      ),
      'Avokado': CropGuide(
        name: 'Avokado',
        plantingSeason: 'Ekim-Mart',
        plantingMethod: 'Fide dikimi, 6-8m aralık',
        wateringSchedule: 'Her 7-10 günde bir',
        wateringAmount: '25-30 litre/ağaç',
        soilRequirements: 'pH 6.0-7.5, iyi drenajlı toprak',
        harvestTime: 'Ekimden 3-4 yıl sonra',
        careTips: 'Güneşli yer seçin, düzenli budama',
        commonProblems: ['Kök çürüklüğü', 'Yaprak hastalığı', 'Zararlı böcek'],
        detailedInfo: {
          'Ekim Derinliği': '60-70 cm',
          'Sıcaklık': '15-30°C (büyüme), 20-35°C (olgunlaşma)',
          'Gübreleme': 'Azot, fosfor, potasyum',
          'Hastalık': 'Verticillium, bakteriyel leke',
          'Zararlı': 'Avokado sineği, yaprak biti'
        },
      ),
      'Mango': CropGuide(
        name: 'Mango',
        plantingSeason: 'Ekim-Mart',
        plantingMethod: 'Fide dikimi, 8-10m aralık',
        wateringSchedule: 'Her 7-10 günde bir',
        wateringAmount: '25-30 litre/ağaç',
        soilRequirements: 'pH 6.0-7.5, iyi drenajlı toprak',
        harvestTime: 'Ekimden 3-4 yıl sonra',
        careTips: 'Güneşli yer seçin, düzenli budama',
        commonProblems: ['Kök çürüklüğü', 'Yaprak hastalığı', 'Zararlı böcek'],
        detailedInfo: {
          'Ekim Derinliği': '60-70 cm',
          'Sıcaklık': '15-30°C (büyüme), 20-35°C (olgunlaşma)',
          'Gübreleme': 'Azot, fosfor, potasyum',
          'Hastalık': 'Verticillium, bakteriyel leke',
          'Zararlı': 'Mango sineği, yaprak biti'
        },
      ),
      'Çay': CropGuide(
        name: 'Çay',
        plantingSeason: 'Ekim-Mart',
        plantingMethod: 'Fide dikimi, 1-1.5m aralık',
        wateringSchedule: 'Her 5-7 günde bir',
        wateringAmount: '8-10 litre/m²',
        soilRequirements: 'pH 4.5-6.0, asitli toprak',
        harvestTime: 'Ekimden 2-3 yıl sonra',
        careTips: 'Serin hava sever, düzenli budama',
        commonProblems: ['Kök çürüklüğü', 'Yaprak hastalığı', 'Zararlı böcek'],
        detailedInfo: {
          'Ekim Derinliği': '30-40 cm',
          'Sıcaklık': '15-25°C (büyüme), 20-30°C (olgunlaşma)',
          'Gübreleme': 'Azot, fosfor, potasyum',
          'Hastalık': 'Mildiyö, bakteriyel leke',
          'Zararlı': 'Çay sineği, yaprak biti'
        },
      ),
      'Fındık': CropGuide(
        name: 'Fındık',
        plantingSeason: 'Ekim-Mart',
        plantingMethod: 'Fide dikimi, 4-5m aralık',
        wateringSchedule: 'Her 10-15 günde bir',
        wateringAmount: '15-20 litre/ağaç',
        soilRequirements: 'pH 5.0-7.0, iyi drenajlı toprak',
        harvestTime: 'Ekimden 3-4 yıl sonra',
        careTips: 'Güneşli yer seçin, düzenli budama',
        commonProblems: ['Kök çürüklüğü', 'Yaprak hastalığı', 'Zararlı böcek'],
        detailedInfo: {
          'Ekim Derinliği': '50-60 cm',
          'Sıcaklık': '15-25°C (büyüme), 20-30°C (olgunlaşma)',
          'Gübreleme': 'Azot, fosfor, potasyum',
          'Hastalık': 'Verticillium, bakteriyel leke',
          'Zararlı': 'Fındık sineği, yaprak biti'
        },
      ),
      'Fasulye': CropGuide(
        name: 'Fasulye',
        plantingSeason: 'Nisan-Mayıs',
        plantingMethod: 'Tohum ekimi, 50-60cm sıra arası',
        wateringSchedule: 'Her 3-4 günde bir',
        wateringAmount: '4-6 litre/m²',
        soilRequirements: 'pH 6.0-7.0, organik madde açısından zengin',
        harvestTime: 'Ekimden 60-80 gün sonra',
        careTips: 'Destek sistemi kullanın, düzenli sulama',
        commonProblems: ['Kök çürüklüğü', 'Yaprak hastalığı', 'Zararlı böcek'],
        detailedInfo: {
          'Ekim Derinliği': '2-3 cm',
          'Sıcaklık': '20-30°C (büyüme), 25-35°C (olgunlaşma)',
          'Gübreleme': 'Azot, fosfor, potasyum',
          'Hastalık': 'Mildiyö, bakteriyel leke',
          'Zararlı': 'Fasulye sineği, yaprak biti'
        },
      ),
      'Lahana': CropGuide(
        name: 'Lahana',
        plantingSeason: 'Şubat-Ekim',
        plantingMethod: 'Fide dikimi, 40-50cm aralık',
        wateringSchedule: 'Her 2-3 günde bir',
        wateringAmount: '4-6 litre/m²',
        soilRequirements: 'pH 6.0-7.0, organik madde açısından zengin',
        harvestTime: 'Ekimden 80-120 gün sonra',
        careTips: 'Serin hava sever, düzenli sulama',
        commonProblems: ['Kök çürüklüğü', 'Yaprak hastalığı', 'Zararlı böcek'],
        detailedInfo: {
          'Ekim Derinliği': '1-2 cm',
          'Sıcaklık': '15-25°C (büyüme), 20-30°C (olgunlaşma)',
          'Gübreleme': 'Azot, fosfor, potasyum',
          'Hastalık': 'Mildiyö, bakteriyel leke',
          'Zararlı': 'Lahana sineği, yaprak biti'
        },
      ),
      'Karnabahar': CropGuide(
        name: 'Karnabahar',
        plantingSeason: 'Şubat-Ekim',
        plantingMethod: 'Fide dikimi, 40-50cm aralık',
        wateringSchedule: 'Her 2-3 günde bir',
        wateringAmount: '4-6 litre/m²',
        soilRequirements: 'pH 6.0-7.0, organik madde açısından zengin',
        harvestTime: 'Ekimden 80-120 gün sonra',
        careTips: 'Serin hava sever, düzenli sulama',
        commonProblems: ['Kök çürüklüğü', 'Yaprak hastalığı', 'Zararlı böcek'],
        detailedInfo: {
          'Ekim Derinliği': '1-2 cm',
          'Sıcaklık': '15-25°C (büyüme), 20-30°C (olgunlaşma)',
          'Gübreleme': 'Azot, fosfor, potasyum',
          'Hastalık': 'Mildiyö, bakteriyel leke',
          'Zararlı': 'Karnabahar sineği, yaprak biti'
        },
      ),
      'Brokoli': CropGuide(
        name: 'Brokoli',
        plantingSeason: 'Şubat-Ekim',
        plantingMethod: 'Fide dikimi, 40-50cm aralık',
        wateringSchedule: 'Her 2-3 günde bir',
        wateringAmount: '4-6 litre/m²',
        soilRequirements: 'pH 6.0-7.0, organik madde açısından zengin',
        harvestTime: 'Ekimden 80-120 gün sonra',
        careTips: 'Serin hava sever, düzenli sulama',
        commonProblems: ['Kök çürüklüğü', 'Yaprak hastalığı', 'Zararlı böcek'],
        detailedInfo: {
          'Ekim Derinliği': '1-2 cm',
          'Sıcaklık': '15-25°C (büyüme), 20-30°C (olgunlaşma)',
          'Gübreleme': 'Azot, fosfor, potasyum',
          'Hastalık': 'Mildiyö, bakteriyel leke',
          'Zararlı': 'Brokoli sineği, yaprak biti'
        },
      ),
      'Tütün': CropGuide(
        name: 'Tütün',
        plantingSeason: 'Mart-Nisan',
        plantingMethod: 'Fide dikimi, 50-60cm aralık',
        wateringSchedule: 'Her 3-4 günde bir',
        wateringAmount: '6-8 litre/m²',
        soilRequirements: 'pH 6.0-7.0, organik madde açısından zengin',
        harvestTime: 'Ekimden 90-120 gün sonra',
        careTips: 'Düzenli sulama, yabani ot temizliği',
        commonProblems: ['Kök çürüklüğü', 'Yaprak hastalığı', 'Zararlı böcek'],
        detailedInfo: {
          'Ekim Derinliği': '1-2 cm',
          'Sıcaklık': '20-30°C (büyüme), 25-35°C (olgunlaşma)',
          'Gübreleme': 'Azot, fosfor, potasyum',
          'Hastalık': 'Mildiyö, bakteriyel leke',
          'Zararlı': 'Tütün sineği, yaprak biti'
        },
      ),
      'Antep Fıstığı': CropGuide(
        name: 'Antep Fıstığı',
        plantingSeason: 'Ekim-Mart',
        plantingMethod: 'Fide dikimi, 6-8m aralık',
        wateringSchedule: 'Her 10-15 günde bir',
        wateringAmount: '20-25 litre/ağaç',
        soilRequirements: 'pH 6.0-8.0, iyi drenajlı toprak',
        harvestTime: 'Ekimden 3-4 yıl sonra',
        careTips: 'Güneşli yer seçin, düzenli budama',
        commonProblems: ['Kök çürüklüğü', 'Yaprak hastalığı', 'Zararlı böcek'],
        detailedInfo: {
          'Ekim Derinliği': '60-70 cm',
          'Sıcaklık': '15-30°C (büyüme), 20-35°C (olgunlaşma)',
          'Gübreleme': 'Azot, fosfor, potasyum',
          'Hastalık': 'Verticillium, bakteriyel leke',
          'Zararlı': 'Antep fıstığı sineği, yaprak biti'
        },
      ),
      'Pamuk': CropGuide(
        name: 'Pamuk',
        plantingSeason: 'Nisan-Mayıs',
        plantingMethod: 'Tohum ekimi, 70-80cm sıra arası',
        wateringSchedule: 'Her 5-7 günde bir',
        wateringAmount: '8-10 litre/m²',
        soilRequirements: 'pH 6.0-7.5, derin toprak',
        harvestTime: 'Ekimden 150-180 gün sonra',
        careTips: 'Düzenli toprak işleme, yabani ot temizliği',
        commonProblems: ['Kök çürüklüğü', 'Yaprak hastalığı', 'Zararlı böcek'],
        detailedInfo: {
          'Ekim Derinliği': '2-3 cm',
          'Sıcaklık': '20-30°C (büyüme), 25-35°C (olgunlaşma)',
          'Gübreleme': 'Azot, fosfor, potasyum',
          'Hastalık': 'Verticillium, bakteriyel leke',
          'Zararlı': 'Pamuk kurdu, yaprak biti'
        },
      ),
      'Kayısı': CropGuide(
        name: 'Kayısı',
        plantingSeason: 'Ekim-Mart',
        plantingMethod: 'Fide dikimi, 4-5m aralık',
        wateringSchedule: 'Her 10-15 günde bir',
        wateringAmount: '15-20 litre/ağaç',
        soilRequirements: 'pH 6.0-7.5, iyi drenajlı toprak',
        harvestTime: 'Ekimden 2-3 yıl sonra',
        careTips: 'Güneşli yer seçin, düzenli budama',
        commonProblems: ['Kök çürüklüğü', 'Yaprak hastalığı', 'Zararlı böcek'],
        detailedInfo: {
          'Ekim Derinliği': '50-60 cm',
          'Sıcaklık': '15-25°C (büyüme), 20-30°C (olgunlaşma)',
          'Gübreleme': 'Azot, fosfor, potasyum',
          'Hastalık': 'Verticillium, bakteriyel leke',
          'Zararlı': 'Kayısı sineği, yaprak biti'
        },
      ),
      'Kırmızı Biber': CropGuide(
        name: 'Kırmızı Biber',
        plantingSeason: 'Nisan-Mayıs',
        plantingMethod: 'Fide dikimi, 40-50cm aralık',
        wateringSchedule: 'Her 2-3 günde bir',
        wateringAmount: '4-6 litre/m²',
        soilRequirements: 'pH 6.0-7.0, organik madde açısından zengin',
        harvestTime: 'Ekimden 80-100 gün sonra',
        careTips: 'Düzenli sulama, güneşli yer seçin',
        commonProblems: ['Meyve dökümü', 'Yaprak sararması', 'Büyüme durması'],
        detailedInfo: {
          'Ekim Derinliği': '1-2 cm',
          'Sıcaklık': '20-30°C (gündüz), 15-20°C (gece)',
          'Gübreleme': 'Kompost, organik gübre',
          'Hastalık': 'Antraknoz, bakteriyel leke',
          'Zararlı': 'Thrips, yaprak biti'
        },
      ),
      'Şeftali': CropGuide(
        name: 'Şeftali',
        plantingSeason: 'Ekim-Mart',
        plantingMethod: 'Fide dikimi, 4-5m aralık',
        wateringSchedule: 'Her 10-15 günde bir',
        wateringAmount: '15-20 litre/ağaç',
        soilRequirements: 'pH 6.0-7.5, iyi drenajlı toprak',
        harvestTime: 'Ekimden 2-3 yıl sonra',
        careTips: 'Güneşli yer seçin, düzenli budama',
        commonProblems: ['Kök çürüklüğü', 'Yaprak hastalığı', 'Zararlı böcek'],
        detailedInfo: {
          'Ekim Derinliği': '50-60 cm',
          'Sıcaklık': '15-25°C (büyüme), 20-30°C (olgunlaşma)',
          'Gübreleme': 'Azot, fosfor, potasyum',
          'Hastalık': 'Verticillium, bakteriyel leke',
          'Zararlı': 'Şeftali sineği, yaprak biti'
        },
      ),
      'Kiraz': CropGuide(
        name: 'Kiraz',
        plantingSeason: 'Ekim-Mart',
        plantingMethod: 'Fide dikimi, 4-5m aralık',
        wateringSchedule: 'Her 10-15 günde bir',
        wateringAmount: '15-20 litre/ağaç',
        soilRequirements: 'pH 6.0-7.5, iyi drenajlı toprak',
        harvestTime: 'Ekimden 2-3 yıl sonra',
        careTips: 'Güneşli yer seçin, düzenli budama',
        commonProblems: ['Kök çürüklüğü', 'Yaprak hastalığı', 'Zararlı böcek'],
        detailedInfo: {
          'Ekim Derinliği': '50-60 cm',
          'Sıcaklık': '15-25°C (büyüme), 20-30°C (olgunlaşma)',
          'Gübreleme': 'Azot, fosfor, potasyum',
          'Hastalık': 'Verticillium, bakteriyel leke',
          'Zararlı': 'Kiraz sineği, yaprak biti'
        },
      ),
      'Armut': CropGuide(
        name: 'Armut',
        plantingSeason: 'Ekim-Mart',
        plantingMethod: 'Fide dikimi, 4-5m aralık',
        wateringSchedule: 'Her 10-15 günde bir',
        wateringAmount: '15-20 litre/ağaç',
        soilRequirements: 'pH 6.0-7.5, iyi drenajlı toprak',
        harvestTime: 'Ekimden 2-3 yıl sonra',
        careTips: 'Güneşli yer seçin, düzenli budama',
        commonProblems: ['Kök çürüklüğü', 'Yaprak hastalığı', 'Zararlı böcek'],
        detailedInfo: {
          'Ekim Derinliği': '50-60 cm',
          'Sıcaklık': '15-25°C (büyüme), 20-30°C (olgunlaşma)',
          'Gübreleme': 'Azot, fosfor, potasyum',
          'Hastalık': 'Verticillium, bakteriyel leke',
          'Zararlı': 'Armut sineği, yaprak biti'
        },
      ),
      'Elma': CropGuide(
        name: 'Elma',
        plantingSeason: 'Ekim-Mart',
        plantingMethod: 'Fide dikimi, 4-5m aralık',
        wateringSchedule: 'Her 10-15 günde bir',
        wateringAmount: '15-20 litre/ağaç',
        soilRequirements: 'pH 6.0-7.5, iyi drenajlı toprak',
        harvestTime: 'Ekimden 2-3 yıl sonra',
        careTips: 'Güneşli yer seçin, düzenli budama',
        commonProblems: ['Kök çürüklüğü', 'Yaprak hastalığı', 'Zararlı böcek'],
        detailedInfo: {
          'Ekim Derinliği': '50-60 cm',
          'Sıcaklık': '15-25°C (büyüme), 20-30°C (olgunlaşma)',
          'Gübreleme': 'Azot, fosfor, potasyum',
          'Hastalık': 'Verticillium, bakteriyel leke',
          'Zararlı': 'Elma sineği, yaprak biti'
        },
      ),
    };
  }
}

