# Sene 2026, iOS 9-10-11 mezarda. O yüzden minimum 13.0 yaptık.
platform :ios, '13.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers! # Bu satır Firebase gibi inatçı paketlerin uymasını sağlar.

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # Bütün o dökülen sürüm hatalarını (iOS 9, 10, 11) topluca 13.0'a çeker.
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      
      # İşte o kırmızı "non-modular header" hatasının ilacı tam olarak bu satır:
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      
      # Apple Silicon (M1/M2/M3) Mac kullanıyorsan uyumluluğu artırır.
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end